/**
* file generated by vergen
**/   

#ifndef __INC_PacConfigVersionHPP
#define __INC_PacConfigVersionHPP

const char FW_VERSION_3S_STRING[9]  = "1.70.7.3";

const UINT8 FW_VERSION_MAJOR  = 1;
const UINT8 FW_VERSION_MINOR  = 70;
const UINT8 FW_VERSION_BUGFIX = 7;
const UINT8 FW_VERSION_BUILD  = 3;

const UINT32 FW_VERSION_UINT32 = 0x01460703;

const char FW_VERSION_STRING[13]  = "V01.70.07.03";
const int FW_VERSION_STRING_LENGTH  = 13;

const char FW_VERSION_STRING_USER[8]  = "V1.70.7";
const int FW_VERSION_STRING_USER_LENGTH  = 8;

const char FW_VERSION_STRING_COMPLETE[10]  = "V1.70.7.3";
const int FW_VERSION_STRING_COMPLETE_LENGTH  = 10;

#ifdef FILE_PacDriveCPP
   int g_lMax4VersionIdStart017007End;
   int g_lMax4Version2IdStart01_70_07_03End;
#endif

#endif //__INC_PacConfigVersionHPP